// Copyright 2024 Meng Zhuo. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package blake2b512 implement Blake2b 512 bits hash algorithm by Linux Kernel Crypto API(kcapi)
package blake2b512

// Code generated by: go run _gen/shash.go
// DO NOT EDIT.
import (
	"hash"

	"github.com/mengzhuo/go-kcapi/shash"
)

const (
	Size      = 64
	BlockSize = 128
)

func New() (hash.Hash, error) {
	return shash.NewHash("blake2b-512", Size, BlockSize)
}
