// Copyright 2024 Meng Zhuo. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package md5 implement MD5 hash algorithm by Linux Kernel Crypto API(kcapi)
package md5

// Code generated by: go run _gen/shash.go
// DO NOT EDIT.
import (
	"hash"

	"github.com/mengzhuo/go-kcapi/shash"
)

const (
	Size      = 16
	BlockSize = 64
)

func New() (hash.Hash, error) {
	return shash.NewHash("md5", Size, BlockSize)
}
