// Copyright 2024 Meng Zhuo. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package sha3_384 implement SHA-3 384 bits hash algorithm by Linux Kernel Crypto API(kcapi)
package sha3_384

// Code generated by: go run _gen/shash.go
// DO NOT EDIT.
import (
	"hash"

	"github.com/mengzhuo/go-kcapi/shash"
)

const (
	Size      = 48
	BlockSize = 104
)

func New() (hash.Hash, error) {
	return shash.NewHash("sha3-384", Size, BlockSize)
}
