// Copyright 2024 Meng Zhuo. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package sha3_256 implement SHA-3 256 bits hash algorithm by Linux Kernel Crypto API(kcapi)
package sha3_256

// Code generated by: go run _gen/shash.go
// DO NOT EDIT.
import (
	"hash"

	"github.com/mengzhuo/go-kcapi/shash"
)

const (
	Size      = 32
	BlockSize = 136
)

func New() (hash.Hash, error) {
	return shash.NewHash("sha3-256", Size, BlockSize)
}
